/**
 * tools/docs.ts
 *
 * MCP tools for eXist-db XQuery documentation lookup.
 * Reads from the local fundocs.json cache (generated by scripts/scrape-fundocs.ts).
 */

import { readFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import type { FundocsCache, FunctionSignature, NamespaceDoc } from "../types/index.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CACHE_PATH = join(__dirname, "../cache/fundocs.json");

// ─── Cache loading ─────────────────────────────────────────────────────────────

let _cache: FundocsCache | null = null;

function loadCache(): FundocsCache {
  if (_cache) return _cache;

  if (!existsSync(CACHE_PATH)) {
    throw new Error(
      `fundocs.json not found at ${CACHE_PATH}.\n` +
        'Run "npm run scrape" to generate the documentation cache first.'
    );
  }

  _cache = JSON.parse(readFileSync(CACHE_PATH, "utf-8")) as FundocsCache;
  return _cache;
}

/**
 * Test-only seam: lets unit tests inject a fixture cache without touching
 * the filesystem. Pass `null` to clear so the next call falls back to disk.
 */
export function __setCacheForTesting(cache: FundocsCache | null): void {
  _cache = cache;
}

// ─── Formatting helpers ────────────────────────────────────────────────────────

function formatSignature(fn: FunctionSignature): string {
  const paramStr = fn.params
    .map((p) => `${p.name} as ${p.type}${cardinalitySuffix(p.cardinality)}`)
    .join(",\n    ");
  return `${fn.name}(\n    ${paramStr || ""}\n) as ${fn.returnType}${cardinalitySuffix(fn.returnCardinality)}`;
}

function cardinalitySuffix(c: string): string {
  switch (c) {
    case "zero or one":     return "?";
    case "zero or more":    return "*";
    case "one or more":     return "+";
    case "exactly one":
    default:                return "";
  }
}

function formatFunction(fn: FunctionSignature, verbose = false): string {
  const lines: string[] = [];
  lines.push(`## ${fn.name}`);
  lines.push(`**Namespace:** \`${fn.namespace}\``);
  lines.push("");
  lines.push("```xquery");
  lines.push(formatSignature(fn));
  lines.push("```");
  lines.push("");
  if (fn.description) {
    lines.push(fn.description);
    lines.push("");
  }
  if (verbose && fn.params.length > 0) {
    lines.push("### Parameters");
    for (const p of fn.params) {
      lines.push(`- \`${p.name}\` *(${p.type}${cardinalitySuffix(p.cardinality)})*: ${p.description}`);
    }
    lines.push("");
  }
  if (fn.deprecated) {
    lines.push(`> ⚠️ **Deprecated:** ${fn.deprecated}`);
    lines.push("");
  }
  return lines.join("\n");
}

// ─── Tool implementations ──────────────────────────────────────────────────────

/**
 * existdb_lookup_function
 * Returns full documentation for one or more matching functions.
 */
export function lookupFunction(args: {
  name: string;           // local name or prefix:localname, e.g. "store" or "xmldb:store"
  namespace?: string;     // optional namespace URI filter
}): string {
  const cache = loadCache();
  const query = args.name.toLowerCase().trim();
  const nsFilter = args.namespace?.toLowerCase();

  const matches: FunctionSignature[] = [];

  for (const ns of cache.namespaces) {
    if (nsFilter && !ns.uri.toLowerCase().includes(nsFilter)) continue;

    for (const fn of ns.functions) {
      const matchesLocal = fn.localName.toLowerCase() === query;
      const matchesFull  = fn.name.toLowerCase() === query;
      const matchesPartial = fn.localName.toLowerCase().includes(query) || fn.name.toLowerCase().includes(query);

      if (matchesFull || matchesLocal || matchesPartial) {
        matches.push(fn);
      }
    }
  }

  if (matches.length === 0) {
    return `No function found matching "${args.name}"${nsFilter ? ` in namespace "${args.namespace}"` : ""}.`;
  }

  const results = matches.slice(0, 10).map((fn) => formatFunction(fn, true)).join("\n---\n\n");
  const footer = matches.length > 10
    ? `\n*Showing 10 of ${matches.length} matches. Refine your query for more specific results.*`
    : "";

  return results + footer;
}

/**
 * existdb_list_namespace_functions
 * Lists all functions in a given namespace.
 */
export function listNamespaceFunctions(args: {
  namespace: string;   // URI or common prefix, e.g. "xmldb" or "http://exist-db.org/xquery/xmldb"
}): string {
  const cache = loadCache();
  const query = args.namespace.toLowerCase().trim();

  const ns = cache.namespaces.find(
    (n) =>
      n.uri.toLowerCase() === query ||
      n.prefix.toLowerCase() === query ||
      n.uri.toLowerCase().includes(query)
  );

  if (!ns) {
    // Show available namespaces/prefixes
    const available = cache.namespaces
      .map((n) => `- \`${n.prefix}\` → \`${n.uri}\` (${n.functions.length} functions)`)
      .join("\n");
    return (
      `Namespace "${args.namespace}" not found.\n\n` +
      `**Available namespaces:**\n${available}`
    );
  }

  if (ns.functions.length === 0) {
    return `Namespace \`${ns.uri}\` is present in the cache but has no documented functions.`;
  }

  const header = [
    `## Namespace: \`${ns.prefix}\``,
    `**URI:** \`${ns.uri}\``,
    `**Location:** \`${ns.location}\``,
    `**Functions:** ${ns.functions.length}`,
    "",
  ].join("\n");

  const fnList = ns.functions
    .map((fn) => {
      const paramSummary = fn.params.map((p) => `${p.name} as ${p.type}${cardinalitySuffix(p.cardinality)}`).join(", ");
      return `### \`${fn.name}(${paramSummary})\`\n${fn.description || "*No description.*"}`;
    })
    .join("\n\n");

  return header + fnList;
}

/**
 * existdb_search_functions
 * Full-text search across all function names and descriptions.
 */
export function searchFunctions(args: {
  keyword: string;
  limit?: number;
}): string {
  const cache = loadCache();
  const kw = args.keyword.toLowerCase().trim();
  const limit = args.limit ?? 15;

  const scored: Array<{ fn: FunctionSignature; score: number }> = [];

  for (const ns of cache.namespaces) {
    for (const fn of ns.functions) {
      let score = 0;
      if (fn.name.toLowerCase().includes(kw))           score += 3;
      if (fn.localName.toLowerCase().startsWith(kw))    score += 2;
      if (fn.description.toLowerCase().includes(kw))    score += 1;
      if (score > 0) scored.push({ fn, score });
    }
  }

  scored.sort((a, b) => b.score - a.score);

  if (scored.length === 0) {
    return `No functions found matching keyword "${args.keyword}".`;
  }

  const results = scored.slice(0, limit).map(({ fn }) => {
    const paramSummary = fn.params.map((p) => `${p.name}`).join(", ");
    return `- \`${fn.name}(${paramSummary})\` — ${fn.description?.slice(0, 100) ?? ""}`;
  });

  const header = `Found ${scored.length} function(s) matching "${args.keyword}"${scored.length > limit ? ` (showing top ${limit})` : ""}:\n`;
  return header + results.join("\n");
}

/**
 * existdb_list_namespaces
 * Returns a summary of all available namespaces in the cache.
 */
export function listNamespaces(args: {
  filter?: "w3c" | "exist" | "expath" | "appmodule" | "all";
}): string {
  const cache = loadCache();
  const filter = args.filter ?? "all";

  const ns = cache.namespaces.filter((n) => {
    if (filter === "all") return true;
    if (filter === "w3c")       return n.uri.includes("w3.org");
    if (filter === "exist")     return n.uri.includes("exist-db.org/xquery");
    if (filter === "expath")    return n.uri.includes("expath.org") || n.uri.includes("exquery.org");
    if (filter === "appmodule") return !n.uri.includes("w3.org") && !n.uri.includes("exist-db.org/xquery") && !n.uri.includes("expath.org");
    return true;
  });

  const lines = [
    `## eXist-db XQuery Namespaces (${filter})`,
    `*Cache generated: ${cache.generated} — eXist-db ${cache.existdbVersion}*`,
    "",
    `| Prefix | Namespace URI | Functions |`,
    `|--------|---------------|-----------|`,
    ...ns.map((n) => `| \`${n.prefix}\` | \`${n.uri}\` | ${n.functions.length} |`),
  ];

  return lines.join("\n");
}

/**
 * existdb_get_xquery_snippet
 * Returns a ready-to-use XQuery code snippet for common patterns involving
 * the given function or module.
 */
export function getXQuerySnippet(args: { topic: string }): string {
  const SNIPPETS: Record<string, string> = {
    "store-document": `(: Store an XML document in eXist-db :)
import module namespace xmldb = "http://exist-db.org/xquery/xmldb";

let $collection := "/db/myapp/data"
let $filename   := "example.xml"
let $doc        := <root><item>Hello eXist!</item></root>
return
  xmldb:store($collection, $filename, $doc)`,

    "fulltext-search": `(: Full-text search with Lucene :)
import module namespace ft = "http://exist-db.org/xquery/lucene";

for $hit in collection("/db/myapp/data")//item[ft:query(., "hello")]
order by ft:score($hit) descending
return $hit`,

    "restxq": `(: RESTful endpoint with RESTXQ annotations :)
module namespace api = "http://myapp.org/api";

import module namespace rest = "http://exquery.org/ns/restxq";
import module namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";

declare
  %rest:GET
  %rest:path("/api/items")
  %output:media-type("application/json")
  %output:method("json")
function api:list-items() {
  array { collection("/db/myapp/data")//item/string(.) }
};`,

    "http-client": `(: HTTP request to an external API :)
import module namespace http = "http://expath.org/ns/http-client";

let $response := http:send-request(
  <http:request method="GET" href="https://api.example.com/data">
    <http:header name="Accept" value="application/json"/>
  </http:request>
)
let $body := $response[2]
return $body`,

    "security": `(: Check permissions and run as specific user :)
import module namespace sm = "http://exist-db.org/xquery/securitymanager";
import module namespace xmldb = "http://exist-db.org/xquery/xmldb";

if (sm:has-access(xs:anyURI("/db/myapp"), "w")) then
  xmldb:store("/db/myapp", "new.xml", <doc/>)
else
  error((), "Access denied")`,

    "transform-xslt": `(: Apply an XSLT transformation :)
import module namespace transform = "http://exist-db.org/xquery/transform";

let $input := doc("/db/myapp/data/source.xml")
let $xsl   := doc("/db/myapp/xslt/transform.xsl")
return
  transform:transform($input, $xsl, ())`,

    "collection-query": `(: Query across a whole collection :)
for $doc in collection("/db/myapp/data")
let $title := $doc//title/string(.)
where contains($title, "example")
order by $title
return <result title="{$title}" uri="{base-uri($doc)}"/>`,
  };

  const key = args.topic.toLowerCase().replace(/\s+/g, "-");
  if (SNIPPETS[key]) {
    return `## XQuery Snippet: ${args.topic}\n\n\`\`\`xquery\n${SNIPPETS[key]}\n\`\`\``;
  }

  const available = Object.keys(SNIPPETS).join(", ");
  return `No snippet found for topic "${args.topic}".\n\nAvailable topics: ${available}`;
}
